# Generated by Django 5.2.13 on 2026-04-21 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiinsight',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='aiinsight',
            old_name='generated_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='aiinsight',
            unique_together={('user', 'period_start', 'period_end', 'type')},
        ),
    ]
