# Generated by Django 5.2.13 on 2026-04-21

from django.db import migrations, models


def forwards_copy_category_to_categories(apps, schema_editor):
    Budget = apps.get_model("budgets", "Budget")
    for budget in Budget.objects.all().iterator():
        if budget.category_id:
            budget.categories.add(budget.category_id)


def noop_reverse(apps, schema_editor):
    # Reverse migration is intentionally a no-op for data copy.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="categories",
            field=models.ManyToManyField(related_name="budgets", to="categories.category"),
        ),
        migrations.RunPython(forwards_copy_category_to_categories, noop_reverse),
        migrations.AlterUniqueTogether(
            name="budget",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="budget",
            name="category",
        ),
        migrations.AlterModelOptions(
            name="budget",
            options={"ordering": ["-month", "-created_at"]},
        ),
    ]
