# Generated by Django 5.2.13 on 2026-04-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_budget_multi_category_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
