# Generated by Django 5.2.13 on 2026-04-21 20:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_budget_name'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_month', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(related_name='recurring_budgets', to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='source_recurring_budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_budgets', to='budgets.recurringbudget'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('source_recurring_budget__isnull', False)), fields=('user', 'source_recurring_budget', 'month'), name='unique_generated_budget_per_template_month'),
        ),
        migrations.AddConstraint(
            model_name='recurringbudget',
            constraint=models.UniqueConstraint(condition=models.Q(('name', ''), _negated=True), fields=('user', 'name', 'start_month'), name='unique_recurring_budget_name_start_month'),
        ),
    ]
